### ISSUE TITLE
lol when i download the already build .exe my anti virus is going crazy xD

### ISSUE THREAD

**Issue by master7720** [notperry1234567890/Perryhook#2]

**Comment by master7720** [comment]
i use bitdefender btw

**Comment by master7720** [comment]
but when i opened the src of the .exe i found nothing so lol

**Comment by notperry1234567890** [comment]
When u convert .py to a .exe with pyinstaller for some reason av's have a stroke idk why I don't think there's really a simple fix for that lol.

**Comment by master7720** [comment]
i trust the .exe bc i looked thro it on dotpeek

**Comment by notperry1234567890** [comment]
> i use bitdefender btw

I have submitted a false positive report to Bitdefender and many other av companies that have falsely flagged this so in 72 hours majority of false positives will hopefully be fixed.

**Comment by master7720** [comment]
ye
